server:
  port: 8800
security:
  ignored: /**
  basic:
    enabled: false
  enable-csrf: false
spring:
  aop:
    auto: false
#    proxy-target-class: true
  security:
    enabled: false
management:
  security:
    enabled: false
zuul:
  ignore-security-headers: false
#  ignored-patterns: /**
  routes:
    oauth2-daemon:
      path: /oauth2/**
      url: http://localhost:8801/oauth
    user-service:
      path: /user/**
      url: http://localhost:8810/user
    tour-service:
      path: /tour/**
      url: http://localhost:8811/tour
#security:
#  sessions: if-required
#  oauth2:
#    client:
#      clientId: test1.staging.xmsymphony.com
#      clientSecret: test
#      access-token-validity-seconds: 30
#      accessTokenUri: http://${daemon.oauth2.host}:${daemon.oauth2.rest.port}/oauth/token
#      userAuthorizationUri: http://${daemon.oauth2.host}:${daemon.oauth2.rest.port}/oauth/authorize
#      authorized-grant-types: client_credentials
##      authorized-grant-types: authorization_code,refresh_token,password,implicit,client_credentials
##      scope: guest,user,admin,read,write
##      tokenName: oauth_token
##      authenticationScheme: query
##      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://${daemon.oauth2.host}:${daemon.oauth2.rest.port}/oauth/dialog
#      preferTokenInfo: false  
##      token-info-uri: https://${daemon.oauth2.host}:${daemon.oauth2.rest.port}/oauth/user