apiVersion: v1
kind: Service
metadata:
  name: tour
  labels:
    app: tour
    provider: lao
    group: com.laegler.lao
    project: tour
    version: {{ .Values.lao.version }}
spec:
  selector:
    app: tour
  ports:
  - name: api
    port: 8080