apiVersion: v1
kind: Service
metadata:
  name: daemon.zuul
  labels:
    app: daemon.zuul
    provider: lao
    group: com.laegler.lao
    project: daemon.zuul
    version: {{ .Values.lao.version }}
spec:
  selector:
    app: daemon.zuul
  ports:
  - name: api
    port: 8080