apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daemon.zuul
  labels:
    app: daemon.zuul
    provider: lao
    group: com.laegler.lao
    project: daemon.zuul
    version: {{ .Values.lao.version }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.upgrade.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.upgrade.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: {{ .Values.upgrade.maxUnavailable }}
  template:
    metadata:
      labels:
        app: daemon.zuul
    spec:
      containers:
      - name: daemon.zuul
        image: {{ .Values.lao.registry }}/daemon.zuul:{{ .Values.lao.version }}
        imagePullPolicy: Always
        env:
        - name: SPRING_CLOUD_CONFIG_GIT_LABEL
          value: {{ .Values.spring.cloud.config.git.label }}
        ports:
        - name: api
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 20
          timeoutSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30