apiVersion: v1
name: lao
version: '0.0.1'
icon: http://example.org/logo.png
home: https://bitbucket.org/tlaegler/lao-logistics
source:
- http://www.example.org
description: lao logistics api
maintainers:
- name: lao
  email: lao@example.org
keywords:
- backend
- api
- rest
- web