create table address (address_id bigint not null auto_increment, address_name varchar(255), city varchar(255), country varchar(255), district varchar(255), latitude varchar(255), longitude varchar(255), postbox varchar(255), state varchar(255), street varchar(255), street_number varchar(255), zipcode varchar(255), primary key (address_id))
create table customer (user_id bigint not null, email varchar(255), password varchar(255), username varchar(255), address_address_id bigint, customer_id bigint, first_name varchar(255), last_name varchar(255), default_payment_payment_id bigint, primary key (user_id))
create table employee (user_id bigint not null, email varchar(255), password varchar(255), username varchar(255), address_address_id bigint, employee_id bigint, licence varchar(255), primary key (user_id))
create table employee_tours (employee_user_id bigint not null, tours_tour_id bigint not null)
create table facility (facility_id bigint not null auto_increment, volume varchar(255), address_address_id bigint, primary key (facility_id))
create table facility_employees (facility_facility_id bigint not null, employees_user_id bigint not null)
create table facility_vehicles (facility_facility_id bigint not null, vehicles_vehicle_id bigint not null)
create table payment (payment_id bigint not null auto_increment, credit_card_holder varchar(255), credit_card_number varchar(255), credit_card_provider varchar(255), paypal_account varchar(255), primary key (payment_id))
create table shipment (shipment_id bigint not null auto_increment, create_date_time datetime, last_edit_date datetime, tracking_uuid binary(255), volume varchar(255), weight varchar(255), customer_user_id bigint, facility_facility_id bigint, payment_payment_id bigint, primary key (shipment_id))
create table shipment_shipment_status (shipment_shipment_id bigint not null, shipment_status_id bigint not null)
create table shipment_status (id bigint not null auto_increment, comment varchar(255), shipment_type varchar(255), employee_user_id bigint, primary key (id))
create table shipment_tours (shipment_shipment_id bigint not null, tours_tour_id bigint not null)
create table tour (tour_id bigint not null auto_increment, scheduled_date_time datetime, scheduled_duration bigint, destination_address_id bigint, employee_user_id bigint, facility_facility_id bigint, vehicle_vehicle_id bigint, primary key (tour_id))
create table tour_shipments (tour_tour_id bigint not null, shipments_shipment_id bigint not null)
create table vehicle (vehicle_id bigint not null auto_increment, licence_plate varchar(255), load_volume varchar(255), load_weight varchar(255), vehicle_type varchar(255), primary key (vehicle_id))
create table vehicle_tours (vehicle_vehicle_id bigint not null, tours_tour_id bigint not null)
alter table employee_tours add constraint UK_crecikpent332xg11bti7f1an unique (tours_tour_id)
alter table facility_employees add constraint UK_ego2ll77i48ebpileqyrrv8bj unique (employees_user_id)
alter table facility_vehicles add constraint UK_mhtgbnfy9168dx798mn5h1oje unique (vehicles_vehicle_id)
alter table shipment_shipment_status add constraint UK_kk2qphyi0ycofnefqceh0pfjm unique (shipment_status_id)
alter table vehicle_tours add constraint UK_okmaf8yqih85ia76jj88l9jqy unique (tours_tour_id)
alter table customer add constraint FK1f7qamig20v877v1lf4ivltie foreign key (default_payment_payment_id) references payment (payment_id)
alter table customer add constraint FK_o9wn00tnvxn4f3rwus9le7lyq foreign key (address_address_id) references address (address_id)
alter table employee add constraint FK_bdjaqpjo3khq8x8kfm4bspgpq foreign key (address_address_id) references address (address_id)
alter table employee_tours add constraint FKn8fns7yfhunqtl4d1bv95ojcw foreign key (tours_tour_id) references tour (tour_id)
alter table employee_tours add constraint FKl5pswor3u4ne1xrnhs6meeq32 foreign key (employee_user_id) references employee (user_id)
alter table facility add constraint FK90ohcf0ca0s9xd0a4t2qpm18g foreign key (address_address_id) references address (address_id)
alter table facility_employees add constraint FK9rsia4u7chygo3aqdyurmvbpa foreign key (employees_user_id) references employee (user_id)
alter table facility_employees add constraint FKjff87l2730eo38w13ofh36u5v foreign key (facility_facility_id) references facility (facility_id)
alter table facility_vehicles add constraint FKnnrfuxxvbq2rshu6eote4t4j1 foreign key (vehicles_vehicle_id) references vehicle (vehicle_id)
alter table facility_vehicles add constraint FK5k6cuaj3lmxvlcwiako30w9rd foreign key (facility_facility_id) references facility (facility_id)
alter table shipment add constraint FK4eyso4aveske6x7kanwgs0st2 foreign key (customer_user_id) references customer (user_id)
alter table shipment add constraint FK116vumo70hiohe3ba5dtxgcep foreign key (facility_facility_id) references facility (facility_id)
alter table shipment add constraint FK4jt0fmmnf4qimufr4plo8nl9f foreign key (payment_payment_id) references payment (payment_id)
alter table shipment_shipment_status add constraint FKlfkxl3yxft5ks6a2b1qjh73uv foreign key (shipment_status_id) references shipment_status (id)
alter table shipment_shipment_status add constraint FK6id294l8g5oqn85nfmt6xxgdo foreign key (shipment_shipment_id) references shipment (shipment_id)
alter table shipment_status add constraint FK9n5cmjvngpjyn77dje20xn9b foreign key (employee_user_id) references employee (user_id)
alter table shipment_tours add constraint FK39el6wr7idvhhstyt4yngs2oc foreign key (tours_tour_id) references tour (tour_id)
alter table shipment_tours add constraint FK1j3xbia2osl0gls3gs99vg8ga foreign key (shipment_shipment_id) references shipment (shipment_id)
alter table tour add constraint FKsm06f6ukcktod1f14i8k9xou foreign key (destination_address_id) references address (address_id)
alter table tour add constraint FKmbhmg2a51s4xuacbsd8le5k8x foreign key (employee_user_id) references employee (user_id)
alter table tour add constraint FKjgdo00nh8di1lyi9qid2b9gft foreign key (facility_facility_id) references facility (facility_id)
alter table tour add constraint FKci3twjnn5dads83rxuwiid504 foreign key (vehicle_vehicle_id) references vehicle (vehicle_id)
alter table tour_shipments add constraint FKh18shrh04cxlkurcs0wo5uram foreign key (shipments_shipment_id) references shipment (shipment_id)
alter table tour_shipments add constraint FKlif84osrniyi4bwpu9byytjus foreign key (tour_tour_id) references tour (tour_id)
alter table vehicle_tours add constraint FKnrv4u9sjmbl0on54jyapydor7 foreign key (tours_tour_id) references tour (tour_id)
alter table vehicle_tours add constraint FK2b4lmhcv44952lxcpcwb7t04e foreign key (vehicle_vehicle_id) references vehicle (vehicle_id)
