create table address (id bigint not null auto_increment, address_name varchar(255), city varchar(255), country varchar(255), district varchar(255), latitude varchar(255), longitude varchar(255), postbox varchar(255), state varchar(255), street varchar(255), street_number varchar(255), zipcode varchar(255), primary key (id))
create table customer (user_id bigint not null, email varchar(255), password varchar(255), username varchar(255), address_id bigint, customer_id bigint, first_name varchar(255), last_name varchar(255), default_payment_id bigint, primary key (user_id))
create table employee (user_id bigint not null, email varchar(255), password varchar(255), username varchar(255), address_id bigint, employee_id bigint, licence varchar(255), primary key (user_id))
create table employee_tours (employee_user_id bigint not null, tours_id bigint not null)
create table facility (id bigint not null auto_increment, volume varchar(255), address_id bigint, primary key (id))
create table facility_employees (facility_id bigint not null, employees_user_id bigint not null)
create table facility_vehicles (facility_id bigint not null, vehicles_id bigint not null)
create table payment (id bigint not null auto_increment, credit_card_holder varchar(255), credit_card_number varchar(255), credit_card_provider varchar(255), paypal_account varchar(255), primary key (id))
create table shipment (shipment_id bigint not null auto_increment, create_date_time datetime, last_edit_date datetime, tracking_uuid binary(255), volume varchar(255), weight varchar(255), customer_user_id bigint, facility_id bigint, payment_id bigint, primary key (shipment_id))
create table shipment_shipment_status (shipment_shipment_id bigint not null, shipment_status_id bigint not null)
create table shipment_status (id bigint not null auto_increment, comment varchar(255), shipment_type varchar(255), employee_user_id bigint, primary key (id))
create table shipment_tours (shipment_shipment_id bigint not null, tours_id bigint not null)
create table tour (id bigint not null auto_increment, scheduled_date_time datetime, scheduled_duration bigint, destination_id bigint, employee_user_id bigint, facility_id bigint, vehicle_id bigint, primary key (id))
create table tour_shipments (tour_id bigint not null, shipments_shipment_id bigint not null)
create table vehicle (id bigint not null auto_increment, licence_plate varchar(255), load_volume varchar(255), load_weight varchar(255), vehicle_type varchar(255), primary key (id))
create table vehicle_tours (vehicle_id bigint not null, tours_id bigint not null)
alter table employee_tours add constraint UK_i73lum4i08uusrjv16hnf68mo unique (tours_id)
alter table facility_employees add constraint UK_ego2ll77i48ebpileqyrrv8bj unique (employees_user_id)
alter table facility_vehicles add constraint UK_jd97veyb8lir9f71oninmqx97 unique (vehicles_id)
alter table shipment_shipment_status add constraint UK_kk2qphyi0ycofnefqceh0pfjm unique (shipment_status_id)
alter table vehicle_tours add constraint UK_er1w67ebidu3ukx64tyliqr7x unique (tours_id)
alter table customer add constraint FKcgns38kj0663y4u8xygp2hh5x foreign key (default_payment_id) references payment (id)
alter table customer add constraint FK_r8whbd0mf9er6vwfr0sclsxkd foreign key (address_id) references address (id)
alter table employee add constraint FK_qrbsk9ljmhfje93me0n7xwdxq foreign key (address_id) references address (id)
alter table employee_tours add constraint FKkb213doks1uvs2pwqih4r48lp foreign key (tours_id) references tour (id)
alter table employee_tours add constraint FKl5pswor3u4ne1xrnhs6meeq32 foreign key (employee_user_id) references employee (user_id)
alter table facility add constraint FKbpfxetgowgub5rnee0iy0nd4c foreign key (address_id) references address (id)
alter table facility_employees add constraint FK9rsia4u7chygo3aqdyurmvbpa foreign key (employees_user_id) references employee (user_id)
alter table facility_employees add constraint FK9jro5oa4eb60sgddm57kybmkd foreign key (facility_id) references facility (id)
alter table facility_vehicles add constraint FKlt999d6an43ryhlyelgyagb2w foreign key (vehicles_id) references vehicle (id)
alter table facility_vehicles add constraint FK8jwg2nkw1ule6finr4py6duuo foreign key (facility_id) references facility (id)
alter table shipment add constraint FK4eyso4aveske6x7kanwgs0st2 foreign key (customer_user_id) references customer (user_id)
alter table shipment add constraint FK9g2su214cv10f417gxpo52rqb foreign key (facility_id) references facility (id)
alter table shipment add constraint FKeunsl3l76wuix4w2hspt45rge foreign key (payment_id) references payment (id)
alter table shipment_shipment_status add constraint FKlfkxl3yxft5ks6a2b1qjh73uv foreign key (shipment_status_id) references shipment_status (id)
alter table shipment_shipment_status add constraint FK6id294l8g5oqn85nfmt6xxgdo foreign key (shipment_shipment_id) references shipment (shipment_id)
alter table shipment_status add constraint FK9n5cmjvngpjyn77dje20xn9b foreign key (employee_user_id) references employee (user_id)
alter table shipment_tours add constraint FK859fxvi1dir13mfem92h45ipt foreign key (tours_id) references tour (id)
alter table shipment_tours add constraint FK1j3xbia2osl0gls3gs99vg8ga foreign key (shipment_shipment_id) references shipment (shipment_id)
alter table tour add constraint FK87uucj7tddcnm3hyfndgojyui foreign key (destination_id) references address (id)
alter table tour add constraint FKmbhmg2a51s4xuacbsd8le5k8x foreign key (employee_user_id) references employee (user_id)
alter table tour add constraint FKkone3s7a7khfr599ds66s1mxx foreign key (facility_id) references facility (id)
alter table tour add constraint FKcwewqtp5rn9qo1jkkj7g1cdd2 foreign key (vehicle_id) references vehicle (id)
alter table tour_shipments add constraint FKh18shrh04cxlkurcs0wo5uram foreign key (shipments_shipment_id) references shipment (shipment_id)
alter table tour_shipments add constraint FK6ruigk86175uuivaw0amtcvj2 foreign key (tour_id) references tour (id)
alter table vehicle_tours add constraint FKefwfm91vll6ro3jaswqg69xt foreign key (tours_id) references tour (id)
alter table vehicle_tours add constraint FKsdg3nwthmiucwxt2ja1ar4g2a foreign key (vehicle_id) references vehicle (id)
